version: "3.5"

services:
  api:
    build:
      context: .
      args:
        - SSH_PRIVATE_KEY
        - NPMRC
        - NODE_ENV=development
    command: ["npm", "dev"]
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/usr/src/app/src
      - ./bin:/usr/src/app/bin
      - ./credentials:/usr/src/app/credentials
      - ./config:/usr/src/app/config
      - ./app.js:/usr/src/app/app.js
      - ./package.json:/usr/src/app/package.json
      - ./knexfile.js:/usr/src/app/knexfile.js
    ports:
      - 9001:8080
